homeassistant:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  elevation: 83
  unit_system: metric
  time_zone: Australia/Sydney
  customize: !include customize.yaml

zone:
  name: Home
  latitude: !secret latitude_loc_home
  longitude: !secret longitude_loc_home
  icon: mdi:home
  radius: 400
  passive: false

zone 2:
  name: Work
  latitude: !secret latitude_loc_zone2
  longitude: !secret longitude_loc_zone2
  radius: 250
  icon: mdi:domain
  passive: false

zone 3:
  name: Work2
  latitude: !secret latitude_loc_zone3
  longitude: !secret longitude_loc_zone3
  icon: mdi:domain
  radius: 200
  passive: false

mqtt:
  broker: m13.cloudmqtt.com
  port: 29813
  client_id: brains
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password

#wemo:

http:
  api_password: !secret http_password
  ssl_certificate: !secret ssl_path
  ssl_key: !secret ssl_key
  ip_ban_enabled: True
  login_attempts_threshold: 3

ifttt:
  key: !secret ifttt_key

#zwave:
  #usb_path: /dev/ttyACM0
  #config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config

####################################################
#                                                  #
#                     Includes             #
#                                                  #
####################################################

###  Devices  ###
#alexa: !include alexa.yaml
camera: !include cameras.yaml
device_tracker: !include device_trackers.yaml
light: !include lights.yaml
media_player: !include media_players.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
switch: !include switches.yaml
alarm_control_panel: !include alarm_control_panel.yaml
automation: !include automation.yaml
group: !include groups.yaml
#input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
#input_slider: !include input_slider.yaml
#notify: !include notify.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
shell_command: !include shell_commands.yaml
climate: !include climate.yaml
####################################################
#                                                  #
#                     Enables             #
#                                                  #
####################################################
logger:
history:
discovery:
sun:
conversation:
logbook:
frontend:

#hdmi_cec:
#  devices:
#    1: TV
#    2:
#      1: Chromecast
#      2: PC
#      3: Pi
