- platform: wemo

#- platform: hyperion
  #host: 192.168.1.125
  #port: 19444
##light 2
#- platform: mqtt
  #name: "BR Node LED"
  #command_topic: "bruh/node1/setpower"
  #rgb_state_topic: "bruh/node1/colorstatus"
  #rgb_command_topic: "bruh/node1/setcolor"
  #optimistic: false
##light 3
#- platform: mqtt
  #name: "Jar LED"
  #command_topic: "bruh/node2/setpower"
  #rgb_state_topic: "bruh/node2/colorstatus"
  #rgb_command_topic: "bruh/node2/setcolor"
  #optimistic: false
##light 4
#- platform: lifx
  #server: 192.168.1.118
  #broadcast: 192.168.1.255
##light 5
#- platform: mqtt
  #name: "Party Button"
  #command_topic: "bruh/partybutt/setpower"
  #rgb_state_topic: "bruh/partybutt/colorstatus"
  #rgb_command_topic: "bruh/partybutt/setcolor"
  #optimistic: false
##light 6
#- platform: mqtt
  #name: "Bathroom LED"
  #command_topic: "bruh/node3/setpower"
  #rgb_state_topic: "bruh/node3/colorstatus"
  #rgb_command_topic: "bruh/node3/setcolor"
  #optimistic: false


