####MEDIA PLAYERS####
#- platform: kodi
#  url: http://192.168.1.125:8080/jsonrpc
#  name: osmc

- platform: onkyo
  host: 192.168.0.8
  name: AVReceiver

- platform: samsungtv
  host: 192.168.0.6
  name: TV
  

#- platform: universal
#  name: Living Room Media
#  children:
#    - media_player.osmc
#    - media_player.chromecast
#  commands:
#    turn_on:
#       service: switch.turn_on
#       data: switch.tv_power
