- platform: wemo
#- platform: rpi_rf
  #gpio: 17
  #switches:
    #bedroom_fan:
      #protocol: 1
      #pulselength: 186
      #code_on: !secret code1_on
      #code_off: !secret code1_off
    #bedroom_lamp:
      #protocol: 1
      #pulselength: 186
      #code_on: !secret code2_on
      #code_off: !secret code2_off
    #livingroom_wall_outlet:
      #protocol: 1
      #pulselength: 186
      #code_on: !secret code3_on
      #code_off: !secret code3_off
    #livingroom_desk_outlet:
      #protocol: 1
      #pulselength: 186
      #code_on: !secret code4_on
      #code_off: !secret code4_off
    #kitchen_outlet:
      #protocol: 1
      #pulselength: 186
      #code_on: !secret code5_on
      #code_off: !secret code5_off
    #bedroom_blinds:
      #protocol: 1
      #pulselength: 186
      #code_on: !secret code6_on
      #code_off: !secret code6_off
    #kitchen_blinds:
      #protocol: 1
      #pulselength: 186
      #code_on: !secret code7_on
      #code_off: !secret code7_off
    #livingroom_blinds:
      #protocol: 1
      #pulselength: 186
      #code_on: !secret code8_on
      #code_off: !secret code8_off
#- platform: command_line
#  switches:
#    pc_power:
#      oncmd: !secret pc_on_cmd
#      offcmd: !secret pc_off_cmd
#    hyperion:
#      oncmd: '/home/hass/bruh2/hyperion/hyperionon.sh'
#      offcmd: '/home/hass/bruh2/hyperion/hyperionoff.sh'
#    tv_power:
#      oncmd:  'kodi-send --host=192.168.1.125 --port=9777 --action="ActivateWindow(10000)"'
#      offcmd:  'kodi-send --host=192.168.1.125 --port=9777 --action="ActivateScreensaver"'
- platform: wake_on_lan
  mac_address: !secret pc_mac
  name: "PC WOL"
  host: "192.168.1.141"
