alias: "CMStormtrooper On"
trigger:
  - platform: state
    entity_id: device_tracker.homeassistant_ben6p
    from: "not_home"
    to: "home"
condition:
  - condition: state
    entity_id: input_select.lock_pc
    state: "disabled"
action:
  service: switch.turn_on
  entity_id: switch.pc_power
