alias: "Home nightime"
trigger:
  - platform: state
    entity_id: group.all_devices
    from: "not_home"
    to: "home"
  - platform: state
    entity_id: sensor.party_button
    state: "Standby"
condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - condition: template
    value_template: "{% if states('input_select.ben_status') != 'sleeping' and states('input_select.cailin_status') != 'sleeping' %}true{% else %}false{% endif %}"
action:
  service: script.all_on