alias: "motion light during night time"
trigger:
  - platform: state
    entity_id: sensor.lr_motion
    state: "motion detected"
  - platform: state
    entity_id: sensor.btr_motion
    state: "motion detected"
  - platform: state
    entity_id: sensor.fibaro_multisensor_motion
    state: "motion detected"
  - platform: state
    entity_id: sensor.aeotec_multisensor_motion
    state: "motion detected"
  - platform: state
    entity_id: sensor.gocontrol_motion
    state: "motion detected"
condition:
  - condition: state
    entity_id: sun.sun
    state: "below_horizon"
  - condition: template
    value_template: "{% if states('input_select.ben_status') == 'sleeping' or states('input_select.cailin_status') == 'sleeping' and now.hour <= 6 %} true {% elif states('input_select.ben_status') == 'sleeping' and states('input_select.cailin_status') == 'sleeping' %}true{% else %}false{% endif %}"
  - condition: state
    entity_id: input_select.company
    state: "disabled"
action:
  service: script.motion_light_lr